### ISSUE TITLE
[Bug] Investigate find_next_player bad arithmetic exception

### ISSUE THREAD

**Issue by antoinerc** [antoinerc/perudocord#11]
18:06:48.110 [error] GenServer {Perudex.GameRegistry, {Perudex.GameServer, 975868273583325184}} terminating
** (ArithmeticError) bad argument in arithmetic expression
    (perudex 0.4.0) lib/game.ex:330: Perudex.Game.find_next_player/1
    (perudex 0.4.0) lib/game.ex:314: Perudex.Game.end_round/2
    (perudex 0.4.0) lib/game_server.ex:30: Perudex.GameServer.handle_call/3
    (stdlib 3.15.1) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.15.1) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.1135.0>): {:move, 134074163194363904, :dudo}
State: %{game: %Perudex.Game{all_players: [134074163194363904, 357327014405079041, 220309979134033922], current_bid: {2, 2}, current_player_id: 134074163194363904, instructions: [], max_dice: 5, players_hands: [%{hand: %Perudex.Hand{dice: [4, 6, 1], remaining_dice: 3}, player_id: 134074163194363904}, %{hand: %Perudex.Hand{dice: [6, 6, 1], remaining_dice: 3}, player_id: 357327014405079041}, %{hand: %Perudex.Hand{dice: [2], remaining_dice: 1}, player_id: 220309979134033922}], remaining_players: [134074163194363904, 357327014405079041, 220309979134033922]}, id: 975868273583325184}
Client #PID<0.1135.0> is alive

    (stdlib 3.15.1) gen.erl:233: :gen.do_call/4
    (elixir 1.13.3) lib/gen_server.ex:1027: GenServer.call/3
    (perudocord 0.1.0) lib/game_process.ex:63: PerudoCord.GameProcess.handle_call/3
    (stdlib 3.15.1) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.15.1) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
 
18:06:48.116 [error] GenServer {PerudoCord.GameRegistry, 975868273583325184} terminating
** (stop) exited in: GenServer.call({:via, Registry, {Perudex.GameRegistry, {Perudex.GameServer, 975868273583325184}}}, {:move, 134074163194363904, :dudo}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArithmeticError) bad argument in arithmetic expression
            (perudex 0.4.0) lib/game.ex:330: Perudex.Game.find_next_player/1
            (perudex 0.4.0) lib/game.ex:314: Perudex.Game.end_round/2
            (perudex 0.4.0) lib/game_server.ex:30: Perudex.GameServer.handle_call/3
            (stdlib 3.15.1) gen_server.erl:721: :gen_server.try_handle_call/4
            (stdlib 3.15.1) gen_server.erl:750: :gen_server.handle_msg/6
            (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.13.3) lib/gen_server.ex:1030: GenServer.call/3
    (perudocord 0.1.0) lib/game_process.ex:63: PerudoCord.GameProcess.handle_call/3
    (stdlib 3.15.1) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.15.1) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.1533.0>): {:dudo, 134074163194363904}
State: %PerudoCord.Game{creator_id: 220309979134033922, game_name: "chicken", id: 975868273583325184, players: [134074163194363904, 357327014405079041, 220309979134033922]}
Client #PID<0.1533.0> is alive

    (stdlib 3.15.1) gen.erl:233: :gen.do_call/4
    (elixir 1.13.3) lib/gen_server.ex:1027: GenServer.call/3
    (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
 
18:06:48.117 [error] Task #PID<0.1533.0> started from #PID<0.1178.0> terminating
** (stop) exited in: GenServer.call(#PID<0.1135.0>, {:dudo, 134074163194363904}, 5000)
    ** (EXIT) exited in: GenServer.call({:via, Registry, {Perudex.GameRegistry, {Perudex.GameServer, 975868273583325184}}}, {:move, 134074163194363904, :dudo}, 5000)
        ** (EXIT) an exception was raised:
            ** (ArithmeticError) bad argument in arithmetic expression
                (perudex 0.4.0) lib/game.ex:330: Perudex.Game.find_next_player/1
                (perudex 0.4.0) lib/game.ex:314: Perudex.Game.end_round/2
                (perudex 0.4.0) lib/game_server.ex:30: Perudex.GameServer.handle_call/3
                (stdlib 3.15.1) gen_server.erl:721: :gen_server.try_handle_call/4
                (stdlib 3.15.1) gen_server.erl:750: :gen_server.handle_msg/6
                (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.13.3) lib/gen_server.ex:1030: GenServer.call/3
    (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.33169565/0 in PerudoCord.ExampleConsumer.start_link/1>
    Args: []

**Comment by antoinerc** [comment]
Fixed here: https://github.com/antoinerc/perudex/pull/8
